# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener:
    enabled: true
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
  # exception:
  #     codes:
  #         'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
  #         'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
  #     messages:
  #         'Acme\HelloBundle\Exception\MyExceptionWithASafeMessage': true
  format_listener:
      rules:
          - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
