events_list:
    path: /api/v1/events
    controller: App\Controller\EventController::listAction
    methods: ['GET']

events_get:
    path: /api/v1/events/{eventId}
    controller: App\Controller\EventController::getAction
    methods: ['GET']
    requirements:
        eventId: '\d+'

events_create:
    path: /api/v1/events
    controller: App\Controller\EventController::createAction
    methods: ['POST']

events_update:
    path: /api/v1/events/{eventId}
    controller: App\Controller\EventController::updateAction
    methods: ['PATCH']
    requirements:
        eventId: '\d+'

events_delete:
    path: /api/v1/events/{eventId}
    controller: App\Controller\EventController::deleteAction
    methods: ['DELETE']
    requirements:
        eventId: '\d+'

tickets_list:
    path: /api/v1/tickets
    controller: App\Controller\TicketController::listAction
    methods: ['GET']

tickets_get:
    path: /api/v1/tickets/{ticketId}
    controller: App\Controller\TicketController::getAction
    methods: ['GET']
    requirements:
        ticketId: '\d+'

tickets_create:
    path: /api/v1/tickets
    controller: App\Controller\TicketController::createAction
    methods: ['POST']

tickets_update:
    path: /api/v1/tickets/{ticketId}
    controller: App\Controller\TicketController::updateAction
    methods: ['PATCH']
    requirements:
        ticketId: '\d+'

tickets_delete:
    path: /api/v1/tickets/{ticketId}
    controller: App\Controller\TicketController::deleteAction
    methods: ['DELETE']
    requirements:
        ticketId: '\d+'

events_overview:
        path: '/'
        controller: App\Controller\EventController::overview
        methods: ['GET']

events_edit_view:
        path: '/events/{eventId}'
        controller: App\Controller\EventController::editView
        methods: ['GET']
        requirements:
            eventId: '\d+'

tickets_overview:
        path: '/events/{eventId}/tickets'
        controller: App\Controller\TicketController::overview
        methods: ['GET']
        requirements:
            eventId: '\d+'

tickets_edit_view:
        path: '/events/{eventId}/tickets/{ticketId}'
        controller: App\Controller\TicketController::editView
        methods: ['GET']
        requirements:
            eventId: '\d+'
            ticketId: '\d+'